//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class İçecekler
    {
        public int ID { get; set; }
        public Nullable<int> ID_Kategori { get; set; }
        public Nullable<int> ID_Menu_Kategori { get; set; }
        public string Tercihler { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    }
}
