//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QRDEREntities : DbContext
    {
        public QRDEREntities()
            : base("name=QRDEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ana_Yemek> Ana_Yemek { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<QRVerisi> QRVerisi { get; set; }
        public virtual DbSet<Tercihler> Tercihler { get; set; }
        public virtual DbSet<Ara_Yemek> Ara_Yemek { get; set; }
        public virtual DbSet<İçecekler> İçecekler { get; set; }
        public virtual DbSet<Tatlılar> Tatlılar { get; set; }
    }
}
