//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tercihler
    {
        public Nullable<int> KategoriID { get; set; }
        public int ID { get; set; }
        public string MenuAdi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
